version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: spring-mvc-board-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=board
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ./docker/mysql/sql:/data/sql

